name: Check Outdated Pod

# on: push
on:
  pull_request:
    branches: ["master"]
    types: ["opened", "reopened", "edited", "synchronize"]
# on: workflow_dispatch

jobs:
  outdatedPods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pods
        run: |
          cd example
          rm podfile.lock
          pod install
      - uses: yatatsu/pod-outdated-check-action@v0.3.0
        id: outdated
        with:
          project_directory: Example
          podspec: Rudder-Amplitude.podspec
          exclude_pods: Rudder
      - name: Notify in slack if there is an outdated Amplitude pod
        run: echo "Successfull"
        if: steps.outdated.outputs.has_any_outdated != 'false' # This will only run if there is an outdated
        run: |
          echo "Successfull"
          echo "${{ steps.outdated.outputs.outdated_pod_info }}"
