name: Check Outdated Pod

on: 
  schedule:
    - cron: '0 0-23 * * *'
  workflow_dispatch:

jobs:
  outdatedPods:
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write' #__This fixed the HttpError: Resource not accessible by integration
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pods
        run: |
          cd example
          rm podfile.lock
          pod install
      - name: Check outdated pod
        uses: yatatsu/pod-outdated-check-action@v0.3.0
        id: outdated
        with:
          project_directory: Example
          podspec: Rudder-Amplitude.podspec
          exclude_pods: Rudder
      - name: Create an issue for updating outdated pod
        if: steps.outdated.outputs.has_any_outdated != 'false'
        uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESCRIPTION: ${{ steps.outdated.outputs.outdated_pod_info }}
          OUTDATED_SDK_NAME: Amplitude
        with:
          filename: .github/outdated-pod-template.md
          update_existing: true
      - name: Log info's
        if: steps.outdated.outputs.has_any_outdated != 'false'
        run: |
          echo ${{ steps.create-issue.outputs. }}
          echo "${{ steps.outdated.outputs.outdated_pod_info }}"
          echo Created issue number ${{ steps.create-issue.outputs.number }}
          echo Created ${{ steps.create-issue.outputs.url }}