name: Check Outdated Pod

on: 
# schedule:
#  - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  outdatedPods:
    permissions:
      issues: 'write' #__This fixed the HttpError: Resource not accessible by integration
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pods
        run: |
          cd example
          rm podfile.lock
          pod install
      - name: Check outdated pod
        uses: yatatsu/pod-outdated-check-action@v0.3.0
        id: check-outdated-pods
        with:
          project_directory: Example
          podspec: Rudder-Amplitude.podspec
          exclude_pods: Rudder
      - name: Create an issue for updating outdated pod
        if: steps.check-outdated-pods.outputs.has_any_outdated != 'false'
        uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESCRIPTION: ${{ steps.check-outdated-pods.outputs.outdated_pod_info }}
          OUTDATED_SDK_NAME: Amplitude
        with:
          filename: .github/outdated-pod-template.md
          update_existing: true
